# handlers file for snmpd
---
- name: restart snmpd
  service:
    name: snmpd
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: restart rsyslog
  service: name=rsyslog state=restarted