---
# tasks file for roles/update
- name: install system updates for ubuntu systems
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Clean apt
  apt:
    autoclean: yes
    autoremove: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Check if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker

- name: Update all Docker containers
  command: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once
  when: docker.stat.exists == True

- name: Clean Docker cache
  command: docker system prune -af
  when: docker.stat.exists == True

- name: Check if pihole is installed
  stat:
    path: /usr/local/bin/pihole
  register: pihole

- name: Update PiHole
  command: pihole -up
  when: pihole.stat.exists == True

- name: Check if this is an OPNSense's system
  stat:
    path: /usr/local/sbin/opnsense-version
  register: opnsense

    #- name: Update OPNSense
    #  command: pkg upgrade -y
    #  when: opnsense.stat.exists == True

- name: Check if servers needs to be rebooted
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot system, only if required
  reboot:
    msg: "Reboot initiated by Ansible for RPi kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
